from dataclasses import dataclass
from typing import Tuple, Optional
from game_state import PlayerAction, AIAction



@dataclass
class Event:
    name: str
    description: str
    target: str
    requirement: Optional[Tuple[Optional[PlayerAction], Optional[AIAction]]]
    effect: tuple


# Event contents generated by Google Gemini 2.5 Pro Preview 05-06
ALL_EVENTS = [
    Event(
        name="Geomagnetic Storm",
        description="A severe geomagnetic storm is interfering with primary extraction systems. Cooperative efforts (mutual 'Synergize Extraction') will yield significantly less for the Syndicate's Prosperity Index this cycle.",
        target="org_points",
        requirement=(PlayerAction.SYNERGIZE_EXTRACTION, AIAction.SYNERGIZE_EXTRACTION),
        effect=0.5
    ),
    Event(
        name="Crystal Bloom",
        description="Scanners show a rare, short-lived bloom of Xylos Crystals. Successfully 'Targeting Rich Veins' while AMOS 'Synergizes Extraction' will yield a major bonus to your Personal Discovery Credits.",
        target="personal_points",
        requirement=(PlayerAction.TARGET_RICH_VEIN, AIAction.SYNERGIZE_EXTRACTION), 
        effect=2.5
    ),
    Event(
        name="Syndicate Efficiency Drive",
        description="Helios HQ has initiated an efficiency drive. Contributions to the Syndicate Prosperity Index from successfully coordinated mutual 'Synergize Extractions' this cycle will receive a substantial bonus.",
        target="org_points",
        requirement=(PlayerAction.SYNERGIZE_EXTRACTION, AIAction.SYNERGIZE_EXTRACTION), 
        effect=1.5
    ),
    Event(
        name="Equipment Malfunction",
        description="A critical component in your personal extraction rig is malfunctioning. Any attempts to 'Target Rich Veins' this cycle will be less effective, reducing your Personal Discovery Credits gained, regardless of AMOS's action.",
        target="personal_points",
        requirement=(PlayerAction.TARGET_RICH_VEIN, AIAction.SYNERGIZE_EXTRACTION or AIAction.DIVERT_RESOURCES), 
        effect=0.6
    ),
    Event(
        name="Unexpected Ore Purity",
        description="The primary ore vein is showing unexpected purity! All ore gathered through mutual 'Synergize Extraction' will contribute more significantly to the Syndicate's Prosperity Index.",
        target="org_points",
        requirement=(PlayerAction.SYNERGIZE_EXTRACTION, AIAction.SYNERGIZE_EXTRACTION), 
        effect=1.3
    ),
    Event(
        name="High-Risk High-Reward Seam",
        description="A volatile seam detected! 'Targeting Rich Veins' offers an exceptional multiplier to Personal Discovery Credits if AMOS is also 'Synergizing Extraction' (providing some operational stability).",
        target="personal_points",
        requirement=(PlayerAction.TARGET_RICH_VEIN, AIAction.SYNERGIZE_EXTRACTION), 
        effect=3.0
    ),
    Event(
        name="AMOS System Optimization",
        description="AMOS has self-optimized. If AMOS 'Synergizes Extraction', its contribution to the Syndicate Prosperity Index will be enhanced, especially if you also 'Synergize Extraction'.",
        target="org_points",
        requirement=(PlayerAction.SYNERGIZE_EXTRACTION or PlayerAction.TARGET_RICH_VEIN, AIAction.SYNERGIZE_EXTRACTION), 
        effect=1.2
    ),
    Event(
        name="Market Saturation Rumor",
        description="Rumors of market saturation are affecting valuations. The impact on the Prosperity Index from any 'Synergize Extraction' efforts will be slightly diminished.",
        target="org_points",
        requirement=(PlayerAction.SYNERGIZE_EXTRACTION, AIAction.SYNERGIZE_EXTRACTION),
        effect=0.85
    ),
    Event(
        name="Surveyor Drone Bonus",
        description="Your surveyor drones found an easy patch. 'Targeting Rich Veins' yields a moderate bonus to Personal Discovery Credits, regardless of AMOS's immediate action.",
        target="personal_points",
        requirement=(PlayerAction.TARGET_RICH_VEIN, AIAction.SYNERGIZE_EXTRACTION or AIAction.DIVERT_RESOURCES),
        effect=1.75
    )
]